#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Layanan {
    InstalasiPipaBaru,
    PerbaikanKebocoranPipa,
    DeteksiKebocoran,
    PembersihanSaluranMampet,
    HydroJetting,
    PenggantianPipaLama,
    PenyambunganPipa,
    PengelasanPipa,
    PemasanganKelengkapanSanitasi,
    PemasanganFilterAir,
    PemasanganWaterHeater,
    PemasanganPompaAir,
    ServisPompaAir,
    PemasanganTangkiAir,
    PemasanganTorenBawahTanah,
    PerbaikanToilet,
    PerbaikanWastafel,
    PemasanganBathtubShower,
    PemasanganPemanasMandi,
    PemasanganMesinCuci,
    PemasanganDishwasher,
}
